on: [push, pull_request]

name: Unit testing

jobs:
  clippy:
    name: Actions - clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true
      - run: cargo fetch
      - run: cargo clippy --all -- -D warnings

  unit-test:
    name: Actions - unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo fetch
      - run: cargo build
      - run: cargo test --all
        env:
          RUST_BACKTRACE: 1